### ISSUE TITLE
import completion not working in neovim

### ISSUE THREAD

**Issue by om-tat-sat** [kevinhalliday/coc-cairo#1]
Hi,
I installed the coc-cairo extension using `:CocInstall coc-cairo` in Neovim. I could not get the completions for import definitions.

In VSCode, the completions work partially. `from a.b import c` - In vscode, completions work after typing out the module names fully - `from a.b`

Could you please help?

Warm Regards,

**Comment by om-tat-sat** [comment]
This extension pulls cairo-ls@0.0.7. The latest version is 0.0.25. How can I get the extension use the latest version of cairo-ls?

Thanks.

**Comment by kevinhalliday** [comment]
@om-tat-sat thanks for flagging this. The original issue with imports is an issue with an older version of cairo-ls. So yes, this extension should use the latest.

I'll bump the dependency and publish a new release now. And I'll work on a better approach to managing cairo-ls versions.

**Comment by kevinhalliday** [comment]
It seems the latest version of cairo-ls is not yet on npm. I've opened an issue here https://github.com/ericglau/cairo-ls/issues/39

**Comment by ericglau** [comment]
@om-tat-sat It should work if you add the [example VIM configuration](https://github.com/neoclide/coc.nvim#example-vim-configuration) to your `~/.vimrc` file.  I've updated the steps in [these instructions](https://github.com/ericglau/cairo-ls/blob/main/VIM.md).

After you've added that to `~/.vimrc`, press Control Space to trigger the completion.

Example:
<img width="651" alt="Screen Shot 2022-07-22 at 2 14 41 PM" src="https://user-images.githubusercontent.com/29640130/180499535-4eeb8dd3-453f-4a93-901f-d6033ed304a5.png">

**Comment by amanusk** [comment]
No dice for me either, only seem to work with the method of installing and editing the coc-settings configuration..

The completion menu pops up without any need for a trigger

**Comment by kevinhalliday** [comment]
Okay I think I'm experiencing the same issue - I'll describe it here. 

Given we point to the `cairo-ls` via config in coc-settings.json to the right virtual environment, I have completions working after the `from` keyword

<img width="830" alt="image" src="https://user-images.githubusercontent.com/14191717/180504658-e0f26778-a700-4abf-927e-93388c6bba71.png">

Completions do not work in the middle of a module name. There is a related issue on cairo-ls here https://github.com/ericglau/cairo-ls/issues/32.  So `from some.<complete me>` would not work.

The issue with this package is that completions do not work after the `import` keyword, but they should. Completions like  `from some.module import <complete me>`. I believe that works in the vscode plugin - @om-tat-sat is that right? 

Hope this is the same issue you all are experiencing. I'll look into it.

**Comment by om-tat-sat** [comment]
Thanks for checking and your reply.
I'm using Neovim. I installed the plugin using :CoCInstall. The only setting I did in coc-settings.json was to point to the correct activate file using cairols.nileVenvCommand and cairols.venvCommand config options.

I have the below setting to trigger completion on pressing _Ctrl-Space_, and to set the syntax for cairo files.
```
inoremap <silent><expr> <c-space> coc#refresh()                                                     
vim.api.nvim_command('au BufNewFile,BufRead *.cairo set filetype=cairo')                            
```


Inside Neovim, the completions after _from_ works after a few attempts. But, after the _import_ keyword, it never worked for me too in Neovim. I see errors like this (checked it with :ConInfo).

```
   19 2022-07-22T20:57:39.235 ERROR (pid:1602545) [server] - uncaughtException Error: Header must provide a Content-Length property.
   20     at AS.onData (/home/<myusername>/.cache/nvim/pack/packer/start/coc.nvim/build/index.js:36:14451)
   21     at Socket.<anonymous> (/home/<myusername>/.cache/nvim/pack/packer/start/coc.nvim/build/index.js:36:14181)
   22     at Socket.emit (node:events:513:28)                                                             
   23     at addChunk (node:internal/streams/readable:324:12)                                             
   24     at readableAddChunk (node:internal/streams/readable:297:9)                                      
   25     at Readable.push (node:internal/streams/readable:234:10)                                        
   26     at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)                                 

```

In vscode, the completions after the import keyword worked for me earlier today, but it doesn't now. Am I missing some settings?

**Comment by kevinhalliday** [comment]
Nope. You're settings are good. I'm getting the same error. I'll look into it. Won't have much time this weekend though.

Also if you wanna try debugging, you can fork this repo, uninstall coc-cairo, and add this to your `init.vim`

```vim
set runtimepath^=/path/to/forked/coc-cairo
```

Then you can just mess around locally and see what gives.

**Comment by om-tat-sat** [comment]
I tried that earlier today. Also, instead of picking the cairo-ls from the npmjs server, I pointed the dependency to a local clone of cairo-ls, and somehow built it and got the out files for that repo. I still see the same issue.

Searching for this error online doesn't help much. I have no knowledge of Nodejs.

Have a nice weekend. Would be great if you are able to look into it sometime next week.

Thanks.

**Comment by kevinhalliday** [comment]
@om-tat-sat turns out the v0.0.7 cairo-ls on npm is the latest version. see here https://github.com/ericglau/cairo-ls/issues/39. the v0.0.25 package  is the vscode exentsion, not the language server

**Comment by kevinhalliday** [comment]
This should be fixed in v0.0.3. v0.0.3 also adds the commands `nile.compile`, `nile.compile.all`, `nile.clean`, and `pytest` - which were configured as callable but not implemented in v0.0.2. Here's [the PR](https://github.com/kevinhalliday/coc-cairo/pull/2/files) if you're interested.

I just tried it out and it seems to be working so closing this issue. Thanks all for your input

If it doesn't work we can reopen

**Comment by om-tat-sat** [comment]
Thanks a lot for fixing this. I tried it now and it works perfectly fine. Thanks again.

**Comment by amanusk** [comment]
I am still stuck with the same issue. Not getting completion for libs

![image](https://user-images.githubusercontent.com/7280933/181909390-ec03b961-c1d5-4091-864e-55f0fa0b894b.png)

Is there anything I need to do post installation?

**Comment by om-tat-sat** [comment]
I tried this in a new virtualenv, and it worked for me. 
Did you try uninstalling and installing the coc-cairo?

**Comment by ericglau** [comment]
@amanusk Does completion work after `from`? There is a [bug](https://github.com/ericglau/cairo-ls/issues/32) where it doesn't work in the middle of a module name.

My suggested post-installation steps are [here](https://github.com/ericglau/cairo-ls/blob/main/VIM.md).

If you see compile error highlighting, then your virtualenv is working fine:
![Screen Shot 2022-07-30 at 10 54 42 AM](https://user-images.githubusercontent.com/29640130/181919912-1ffc05c4-b4ea-4780-803a-59820c9969f7.png)

**Comment by amanusk** [comment]
Thanks @ericglau.

I indeed get compilation errors and I do get completion after `import`, but not after `from`

![image](https://user-images.githubusercontent.com/7280933/181921998-188a7767-d70a-429e-955c-d89bb2e4d08e.png)


With your previous instructions, all that works + I get completion after `from` and in the middle of a module name

![image](https://user-images.githubusercontent.com/7280933/181923492-b23a61db-9789-4867-912c-672283e9f7a1.png)
